koji-ssl-admin: pkcs12 password must be bytes
In the latest python-cryptography releases, the openssl backend's
load_key_and_certificates_from_pkcs12() method expect a bytes object.
The cryptography library raises:

  TypeError: password must be bytes-like

Pass in the "koji" password as a bytestring.